#!/bin/bash

mkdir -p $SOURCE_DIR $WORK_DIR $LOG_DIR
touch /var/lib/pkg/db

export CFLAGS CXXFLAGS MAKEFLAGS

fetch() {
	filename=$(basename $1)
	if [ -f $SOURCE_DIR/$filename ]; then
		return 0
	else
		if [ -f $SOURCE_DIR/$filename.part ]; then
			wget -c --output-document=$SOURCE_DIR/$filename.part $1
		else
			wget --output-document=$SOURCE_DIR/$filename.part $1
		fi
		if [ $? = 0 ]; then
			mv $SOURCE_DIR/$filename.part $SOURCE_DIR/$filename
		else
			return 1
		fi
	fi
}

registerpkg() {
	sed "/^$1 /d" -i /var/lib/pkg/db
	echo "$1 $2" >> /var/lib/pkg/db
	[ $(type -p ldconfig) ] && ldconfig
	echo "::: $1 $2 installed :::"
}
