#!/bin/bash

set -e

. /etc/pkg/pkg.conf
. /var/lib/pkg/functions

name=$(basename $0)
version=7.0.7
url=http://roy.marples.name/downloads/dhcpcd/dhcpcd-$version.tar.xz

fetch $url
fetch http://anduin.linuxfromscratch.org/BLFS/blfs-bootscripts/blfs-bootscripts-20180105.tar.xz

rm -fr $WORK_DIR/$name-$version
tar -xvf $SOURCE_DIR/$(basename $url) -C $WORK_DIR

cd $WORK_DIR/$name-$version
{ time \
   {
	./configure --libexecdir=/lib/dhcpcd \
				--dbdir=/var/lib/dhcpcd
	make
	make install
	tar -xvf $SOURCE_DIR/blfs-bootscripts-20180105.tar.xz
	cd blfs-bootscripts-20180105
	make install-service-dhcpcd
   }
} 2>&1 | tee -a $LOG_DIR/$(basename $0).log

if [ $PIPESTATUS -ne 0 ]; then exit 1; fi;

rm -fr $WORK_DIR/$name-$version

registerpkg $(basename $0) $version

exit 0
