#!/bin/bash

set -e

. /etc/pkg/pkg.conf
. /var/lib/pkg/functions

name=$(basename $0)
version=4.6.0
url=http://ftp.gnu.org/gnu/findutils/findutils-$version.tar.gz

fetch $url

rm -fr $WORK_DIR/$name-$version
tar -xvf $SOURCE_DIR/$(basename $url) -C $WORK_DIR

cd $WORK_DIR/$name-$version
{ time \
   {
	sed -i 's/test-lock..EXEEXT.//' tests/Makefile.in
	sed -i 's/IO_ftrylockfile/IO_EOF_SEEN/' gl/lib/*.c
	sed -i '/unistd/a #include <sys/sysmacros.h>' gl/lib/mountlist.c
	echo "#define _IO_IN_BACKUP 0x100" >> gl/lib/stdio-impl.h

	./configure --prefix=/usr --localstatedir=/var/lib/locate
	make
	make install
	mv -v /usr/bin/find /bin
	sed -i 's|find:=${BINDIR}|find:=/bin|' /usr/bin/updatedb
   }
} 2>&1 | tee -a $LOG_DIR/$(basename $0).log

if [ $PIPESTATUS -ne 0 ]; then exit 1; fi;

rm -fr $WORK_DIR/$name-$version

registerpkg $(basename $0) $version

exit 0
