#!/bin/bash

set -e

. /etc/pkg/pkg.conf
. /var/lib/pkg/functions

name=$(basename $0)
version=0.19.8.1
url=http://ftp.gnu.org/gnu/gettext/gettext-$version.tar.xz

fetch $url

rm -fr $WORK_DIR/$name-$version
tar -xvf $SOURCE_DIR/$(basename $url) -C $WORK_DIR

cd $WORK_DIR/$name-$version
{ time \
   {
	sed -i '/^TESTS =/d' gettext-runtime/tests/Makefile.in &&
	sed -i 's/test-lock..EXEEXT.//' gettext-tools/gnulib-tests/Makefile.in

	sed -e '/AppData/{N;N;p;s/\.appdata\./.metainfo./}' \
	    -i gettext-tools/its/appdata.loc

	./configure --prefix=/usr    \
		    --disable-static \
		    --docdir=/usr/share/doc/gettext-$version
	make
	make install
	chmod -v 0755 /usr/lib/preloadable_libintl.so
   }
} 2>&1 | tee -a $LOG_DIR/$(basename $0).log

if [ $PIPESTATUS -ne 0 ]; then exit 1; fi;

rm -fr $WORK_DIR/$name-$version

registerpkg $(basename $0) $version

exit 0
