#!/bin/bash

set -e

. /etc/pkg/pkg.conf
. /var/lib/pkg/functions

name=$(basename $0)
version=4.18.0
url=https://www.kernel.org/pub/linux/utils/net/iproute2/iproute2-$version.tar.xz

fetch $url

rm -fr $WORK_DIR/$name-$version
tar -xvf $SOURCE_DIR/$(basename $url) -C $WORK_DIR

cd $WORK_DIR/$name-$version
{ time \
   {
	sed -i /ARPD/d Makefile
	rm -fv man/man8/arpd.8

	sed -i 's/.m_ipt.o//' tc/Makefile

	make
	make DOCDIR=/usr/share/doc/iproute2-$version install
   }
} 2>&1 | tee -a $LOG_DIR/$(basename $0).log

if [ $PIPESTATUS -ne 0 ]; then exit 1; fi;

rm -fr $WORK_DIR/$name-$version

registerpkg $(basename $0) $version

exit 0
