#!/bin/bash

set -e

. /etc/pkg/pkg.conf
. /var/lib/pkg/functions

name=linux
version=4.19.2

fetch https://cdn.kernel.org/pub/linux/kernel/v4.x/linux-$version.tar.xz

rm -fr $WORK_DIR/$name-$version
tar -xvf $SOURCE_DIR/linux-$version.tar.xz -C $WORK_DIR

cd $WORK_DIR/$name-$version
{ time \
   {
	make mrproper
	make INSTALL_HDR_PATH=dest headers_install
	find dest/include \( -name .install -o -name ..install.cmd \) -delete
	cp -rv dest/include/* /usr/include
   }
} 2>&1 | tee -a $LOG_DIR/$(basename $0).log

if [ $PIPESTATUS -ne 0 ]; then exit 1; fi;

rm -fr $WORK_DIR/$name-$version

registerpkg $(basename $0) $version

exit 0
