#!/bin/bash

set -e

. /etc/pkg/pkg.conf
. /var/lib/pkg/functions

name=m4
version=1.4.18
url=http://ftp.gnu.org/gnu/m4/m4-1.4.18.tar.xz

fetch $url

rm -fr $WORK_DIR/$name-$version
tar -xvf $SOURCE_DIR/$(basename $url) -C $WORK_DIR

cd $WORK_DIR/$name-$version
{ time \
   {
		sed -i 's/IO_ftrylockfile/IO_EOF_SEEN/' lib/*.c
		echo "#define _IO_IN_BACKUP 0x100" >> lib/stdio-impl.h
		
		./configure --prefix=/usr
		make
		make install
   }
} 2>&1 | tee -a $LOG_DIR/$(basename $0).log

if [ $PIPESTATUS -ne 0 ]; then exit 1; fi;

rm -fr $WORK_DIR/$name-$version

registerpkg $(basename $0) $version

exit 0
