#!/bin/bash

set -e

. /etc/pkg/pkg.conf
. /var/lib/pkg/functions

name=man-pages
version=4.16

fetch https://www.kernel.org/pub/linux/docs/man-pages/man-pages-$version.tar.xz

rm -fr $WORK_DIR/$name-$version
tar -xvf $SOURCE_DIR/$name-$version.tar.xz -C $WORK_DIR

cd $WORK_DIR/$name-$version
{ time \
   {
	make install
   }
} 2>&1 | tee -a $LOG_DIR/$(basename $0).log

if [ $PIPESTATUS -ne 0 ]; then exit 1; fi;

rm -fr $WORK_DIR/$name-$version

registerpkg $(basename $0) $version

exit 0
