#!/bin/bash

set -e

. /etc/pkg/pkg.conf
. /var/lib/pkg/functions

name=$(basename $0)
version=2.8.4
url=http://download.savannah.gnu.org/releases/man-db/man-db-$version.tar.xz

fetch $url

rm -fr $WORK_DIR/$name-$version
tar -xvf $SOURCE_DIR/$(basename $url) -C $WORK_DIR

cd $WORK_DIR/$name-$version
{ time \
   {
	./configure --prefix=/usr                        \
		    --docdir=/usr/share/doc/man-db-$version \
		    --sysconfdir=/etc                    \
		    --disable-setuid                     \
		    --enable-cache-owner=bin             \
		    --with-browser=/usr/bin/lynx         \
		    --with-vgrind=/usr/bin/vgrind        \
		    --with-grap=/usr/bin/grap            \
		    --with-systemdtmpfilesdir=
	make
	make install
   }
} 2>&1 | tee -a $LOG_DIR/$(basename $0).log

if [ $PIPESTATUS -ne 0 ]; then exit 1; fi;

rm -fr $WORK_DIR/$name-$version

registerpkg $(basename $0) $version

exit 0
