#!/bin/bash

set -e

. /etc/pkg/pkg.conf
. /var/lib/pkg/functions

name=$(basename $0)
version=0.23.14
url=https://github.com/p11-glue/p11-kit/releases/download/$version/p11-kit-$version.tar.gz

fetch $url

rm -fr $WORK_DIR/$name-$version
tar -xvf $SOURCE_DIR/$(basename $url) -C $WORK_DIR

cd $WORK_DIR/$name-$version
{ time \
   {
	sed '20,$ d' -i trust/trust-extract-compat.in &&
cat >> trust/trust-extract-compat.in << "EOF"
echo "Please create an OpenSSL Trusted Certificate with appropriate"
echo "trust arguments in /etc/ssl/local/ and run '/usr/sbin/make-ca -f'"
echo "as the root user."
exit 1
EOF

	./configure --prefix=/usr     \
		    --sysconfdir=/etc \
		    --with-trust-paths=/etc/pki/anchors
	make
	make install
   }
} 2>&1 | tee -a $LOG_DIR/$(basename $0).log

if [ $PIPESTATUS -ne 0 ]; then exit 1; fi;

rm -fr $WORK_DIR/$name-$version

registerpkg $(basename $0) $version

exit 0
