#!/bin/bash

set -e

. /etc/pkg/pkg.conf
. /var/lib/pkg/functions

name=$(basename $0)
version=5.28.0
url=https://www.cpan.org/src/5.0/perl-$version.tar.xz

fetch $url

rm -fr $WORK_DIR/$name-$version
tar -xvf $SOURCE_DIR/$(basename $url) -C $WORK_DIR

cd $WORK_DIR/$name-$version
{ time \
   {
	echo "127.0.0.1 localhost lfs" > /etc/hosts

	export BUILD_ZLIB=False
	export BUILD_BZIP2=0

	sh Configure -des -Dprefix=/usr                 \
		          -Dvendorprefix=/usr           \
		          -Dman1dir=/usr/share/man/man1 \
		          -Dman3dir=/usr/share/man/man3 \
		          -Dpager="/usr/bin/less -isR"  \
		          -Duseshrplib                  \
		          -Dusethreads
	make
	make install
	unset BUILD_ZLIB BUILD_BZIP2
   }
} 2>&1 | tee -a $LOG_DIR/$(basename $0).log

if [ $PIPESTATUS -ne 0 ]; then exit 1; fi;

rm -fr $WORK_DIR/$name-$version

registerpkg $(basename $0) $version

exit 0
