#!/bin/bash

set -e

. /etc/pkg/pkg.conf
. /var/lib/pkg/functions

name=Python
version=3.7.2
url=https://www.python.org/ftp/python/$version/Python-$version.tar.xz

fetch $url

rm -fr $WORK_DIR/$name-$version
tar -xvf $SOURCE_DIR/$(basename $url) -C $WORK_DIR

cd $WORK_DIR/$name-$version
{ time \
   {
	./configure --prefix=/usr       \
		    --enable-shared     \
		    --with-system-expat \
		    --with-system-ffi   \
		    --with-ensurepip=yes
	make
	make install
	chmod -v 755 /usr/lib/libpython3.7m.so
	chmod -v 755 /usr/lib/libpython3.so
   }
} 2>&1 | tee -a $LOG_DIR/$(basename $0).log

if [ $PIPESTATUS -ne 0 ]; then exit 1; fi;

rm -fr $WORK_DIR/$name-$version

registerpkg $(basename $0) $version

exit 0
