#!/bin/bash

set -e

. /etc/pkg/pkg.conf
. /var/lib/pkg/functions

name=$(basename $0)
version=4.6
url=https://github.com/shadow-maint/shadow/releases/download/$version/shadow-$version.tar.xz

fetch $url

rm -fr $WORK_DIR/$name-$version
tar -xvf $SOURCE_DIR/$(basename $url) -C $WORK_DIR

cd $WORK_DIR/$name-$version
{ time \
   {
	sed -i 's/groups$(EXEEXT) //' src/Makefile.in
	find man -name Makefile.in -exec sed -i 's/groups\.1 / /'   {} \;
	find man -name Makefile.in -exec sed -i 's/getspnam\.3 / /' {} \;
	find man -name Makefile.in -exec sed -i 's/passwd\.5 / /'   {} \;
	
	sed -i -e 's@#ENCRYPT_METHOD DES@ENCRYPT_METHOD SHA512@' \
		-e 's@/var/spool/mail@/var/mail@' etc/login.defs
		
	sed -i 's/1000/999/' etc/useradd
	
	./configure --sysconfdir=/etc --with-group-name-max-length=32
	make
	make install
	mv -v /usr/bin/passwd /bin
   }
} 2>&1 | tee -a $LOG_DIR/$(basename $0).log

if [ $PIPESTATUS -ne 0 ]; then exit 1; fi;

rm -fr $WORK_DIR/$name-$version

registerpkg $(basename $0) $version

exit 0
