#!/bin/bash

set -e

. /etc/pkg/pkg.conf
. /var/lib/pkg/functions

name=$(basename $0)
version=2.3.2
url=http://www.jedsoft.org/releases/slang/slang-$version.tar.bz2

fetch $url

rm -fr $WORK_DIR/$name-$version
tar -xvf $SOURCE_DIR/$(basename $url) -C $WORK_DIR

cd $WORK_DIR/$name-$version
{ time \
   {
	./configure --prefix=/usr \
            --sysconfdir=/etc \
            --with-readline=gnu
	make -j1
	make -j1 install_doc_dir=/usr/share/doc/slang-$version   \
		 SLSH_DOC_DIR=/usr/share/doc/slang-$version/slsh \
		 install-all

	chmod -v 755 /usr/lib/libslang.so.2.3.2 \
				 /usr/lib/slang/v2/modules/*.so
   }
} 2>&1 | tee -a $LOG_DIR/$(basename $0).log

if [ $PIPESTATUS -ne 0 ]; then exit 1; fi;

rm -fr $WORK_DIR/$name-$version

registerpkg $(basename $0) $version

exit 0
