#!/bin/bash

set -e

. /etc/pkg/pkg.conf
. /var/lib/pkg/functions

name=$(basename $0)
version=6.5
url=http://ftp.gnu.org/gnu/texinfo/texinfo-$version.tar.xz

fetch $url

rm -fr $WORK_DIR/$name-$version
tar -xvf $SOURCE_DIR/$(basename $url) -C $WORK_DIR

cd $WORK_DIR/$name-$version
{ time \
   {
	sed -i '5481,5485 s/({/(\\{/' tp/Texinfo/Parser.pm

	./configure --prefix=/usr --disable-static
	make
	make install
	pushd /usr/share/info
	rm -v dir
	for f in *
	  do install-info $f dir 2>/dev/null
	done
	popd
   }
} 2>&1 | tee -a $LOG_DIR/$(basename $0).log

if [ $PIPESTATUS -ne 0 ]; then exit 1; fi;

rm -fr $WORK_DIR/$name-$version

registerpkg $(basename $0) $version

exit 0
