#!/bin/bash

set -e

. /etc/pkg/pkg.conf
. /var/lib/pkg/functions

name=$(basename $0)
version=2.32.1
url=https://www.kernel.org/pub/linux/utils/util-linux/v${version::4}/util-linux-$version.tar.xz

fetch $url

rm -fr $WORK_DIR/$name-$version
tar -xvf $SOURCE_DIR/$(basename $url) -C $WORK_DIR

cd $WORK_DIR/$name-$version
{ time \
   {
	mkdir -pv /var/lib/hwclock

	rm -vf /usr/include/{blkid,libmount,uuid}

		./configure ADJTIME_PATH=/var/lib/hwclock/adjtime   \
		    --docdir=/usr/share/doc/util-linux-$version \
		    --disable-chfn-chsh  \
		    --disable-login      \
		    --disable-nologin    \
		    --disable-su         \
		    --disable-setpriv    \
		    --disable-runuser    \
		    --disable-pylibmount \
		    --disable-static     \
		    --without-python     \
		    --without-systemd    \
		    --without-systemdsystemunitdir
	make
	make install
   }
} 2>&1 | tee -a $LOG_DIR/$(basename $0).log

if [ $PIPESTATUS -ne 0 ]; then exit 1; fi;

rm -fr $WORK_DIR/$name-$version

registerpkg $(basename $0) $version

exit 0
