#!/bin/bash

set -e

. /etc/pkg/pkg.conf
. /var/lib/pkg/functions

name=$(basename $0)
version=1.19.5
url=https://ftp.gnu.org/gnu/wget/wget-$version.tar.gz

fetch $url

rm -fr $WORK_DIR/$name-$version
tar -xvf $SOURCE_DIR/$(basename $url) -C $WORK_DIR

cd $WORK_DIR/$name-$version
{ time \
   {
	./configure --prefix=/usr      \
		    --sysconfdir=/etc  \
		    --with-ssl=openssl
	make
	make install
   }
} 2>&1 | tee -a $LOG_DIR/$(basename $0).log

if [ $PIPESTATUS -ne 0 ]; then exit 1; fi;

rm -fr $WORK_DIR/$name-$version

registerpkg $(basename $0) $version

exit 0
