#!/bin/sh

[ -f venom-vm.img ] || {
	qemu-img create -f qcow2 venom-vm.img 50G
}

exec qemu-system-x86_64 -enable-kvm \
        -cpu host \
        -drive file=venom-vm.img,if=virtio \
        -netdev user,id=vmnic,hostname=Venom \
        -device virtio-net,netdev=vmnic \
        -device virtio-rng-pci \
        -m 2G \
        -smp 4 \
        -monitor stdio \
        -name "VenomLinux VM" \
        -boot d \
        -cdrom $@
