#!/bin/sh

PORTSDIR="$(dirname $(dirname $(realpath $0)))"
SCRIPTDIR="$(dirname $(realpath $0))"

[ -f "$PORTSDIR"/qemu-vm.img ] || {
	qemu-img create -f qcow2 "$PORTSDIR"/qemu-vm.img 50G
}

qemu-system-x86_64 -enable-kvm \
        -cpu host \
        -drive file="$PORTSDIR"/qemu-vm.img,if=virtio \
        -device virtio-rng-pci \
        -m 2G \
        -smp 4 \
        -monitor stdio \
        -name "VenomLinux VM" \
        -boot d \
        -cdrom $@

rm -f "$PORTSDIR"/qemu-vm.img

exit 0
