#!/bin/sh

[ -f ./outdate ] || {
	echo "please check update first"
}

while read -r port oldver a newver; do
	p=${port##*/}
	case $p in
		python3) p=python;;
		gcc) p="$p-pass1 $p-pass2 libstdc++";;
		binutils) p="$p-pass1 $p-pass2";;
		ca-certificates) p=certs;;
	esac
	echo -n "Update $port to $newver"
	sed "s/^version=.*/version=$newver/" -i $port/Pkgfile
	[ $? = 0 ] && echo " OK" || echo " failed"
	for i in $p; do
		[ -f ../toolchain/*-$i ] && {
			echo -n "Update $i (toolchain) to $newver"
			sed "s/^version=.*/version=$newver/" -i ../toolchain/*-$i
			[ $? = 0 ] && echo " OK" || echo " failed"
		}
	done
done < outdate
