#!/bin/sh

if [ -f /lib/modules/KERNELVERSION ]; then
	kver=$(cat /lib/modules/KERNELVERSION)
else
	kver=$(file /boot/vmlinuz-lfs | cut -d ' ' -f9)
fi

mkinitramfs -q -k $kver -o /boot/initrd-lfs.img
depmod $kver

