#!/bin/bash -e

source $(dirname $0)/functions
source $(dirname $0)/pkgversion

filename=$(echo $0 | rev | cut -d / -f1 | rev)

TMP=${TMP:-/tmp/build}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-$(dirname $0)/src}

NAME=gzip
VERSION=${GZIP_VER}

fetch "http://ftp.gnu.org/gnu/gzip/gzip-$GZIP_VER.tar.xz" $SRC

[ "$1" = "fetch" ] && exit 0

rm -fr $TMP
mkdir -p $TMP $LOG $SRC

tar xf $SRC/$tarballname -C $TMP

{ time \
   {

	cd $TMP/$NAME-$VERSION

	#fixes required by glibc-2.28
	sed -i 's/IO_ftrylockfile/IO_EOF_SEEN/' lib/*.c
	echo "#define _IO_IN_BACKUP 0x100" >> lib/stdio-impl.h
	
	./configure --prefix=/tools
	make
	make install
	
	}
} 2>&1 | tee $LOG/$filename.log
    
[ $PIPESTATUS = 0 ] && echo "$NAME-$VERSION" > /tools/$filename || exit $PIPESTATUS

rm -fr $TMP
